'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetSupplier

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rBL_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rBL_search As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txtSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSearch As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''lnkFind control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkFind As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lnkAddNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAddNew As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''example control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents example As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''t_RefNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_RefNO As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''t_SQAQ_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Contact As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''dd_SQASu_Subject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_SQASu_Subject As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dd_SQAM_SUBName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_SQAM_SUBName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''t_SQAM_SUBsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAM_SUBsName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''_ISCComProfile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents _ISCComProfile As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txtidno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidno As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fileup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fileup As Global.System.Web.UI.HtmlControls.HtmlInputFile

    '''<summary>
    '''submitbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents submitbtn As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
End Class
