'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SetSupplierB1

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lnkNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkNew As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbPosition As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbFlag control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFlag As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAM_SUBsName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAM_SUBsName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Date As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_Contact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Contact As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQASu_Subject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQASu_Subject As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAM_SUBName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAM_SUBName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div14 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I12 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAM_TMaterials control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAM_TMaterials As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAM_Type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAM_Type As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAM_ProductT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAM_ProductT As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_FouPro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_FouPro As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_SevLev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_SevLev As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_DetPro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_DetPro As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_Coil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Coil As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_DO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_DO As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_InDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_InDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_NoPro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_NoPro As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_Note control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Note As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAS_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAS_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_RCISolProDet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_RCISolProDet As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_ExpTyp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_ExpTyp As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_ExpTypCou control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_ExpTypCou As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_Res control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_Res As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_ResDet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_ResDet As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_ResDetOth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_ResDetOth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAA_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAA_Name As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''t_SQAQ_AttOth control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_AttOth As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Div4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''t_SQAQ_SIName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents t_SQAQ_SIName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''Div6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''I4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents I4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''example_RelUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents example_RelUpload As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnReset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReset As Global.System.Web.UI.WebControls.LinkButton
End Class
